#!/bin/bash
set -e;
set -u;
set -o pipefail;

R='\033[0;31m'; LR='\033[1;31m'; G='\033[0;32m'; LG='\033[1;32m'
P='\033[0;35m'; LP='\033[1;35m'; C='\033[0;36m'; LC='\033[1;36m'
Y='\033[0;33m'; LY='\033[1;33m'; B='\033[0;34m'; LB='\033[1;34m'; N='\033[0m'

module=repl
compiler=gcc
workdir=$HOME/dvsa/doti/lib/c/clp/
srcdir=src/
builddir=target/
out=$module
out_path="${builddir}${out}"

module_rel_path=${srcdir}${module}.c
module_abs_path=${workdir}${srcdir}${module}.c

out_rel_path=${builddir}${module}
out_abs_path=${workdir}${builddir}${module}

builddur=""
rundur=""

buildcmd="${compiler} ${module_rel_path} -std=c99 -Wall -o ${out_path}"
runcmd="${out_abs_path}"

function set_paths_from_module() {
    out=$module
    module_rel_path=${srcdir}${module}.c
    module_abs_path=${workdir}${srcdir}${module}.c
    out_rel_path=${builddir}${module}
    out_abs_path=${workdir}${builddir}${module}
    buildcmd="${compiler} ${module_rel_path} -std=c99 -Wall -o ${out_path}"
    runcmd="${out_abs_path}"


}
function parse_args() {
    if [ "$#" -gt "1" ]; then
        for $arg in $@
        do
            case $arg in
                -m|--module)   module=$2   ;;
                -c|--compiler) compiler=$2 ;;
                -o|--out)      out=$2      ;;
                -b|--builddir) builddir=$2 ;;
                -w|--workdir)  workdir=$2  ;;
                -s|--srcdir)   srcdir=$2   ;;
                *)
                    echo -e "${R}Invalid opt: ${Y}-$arg${N}" 1>&2
                    exit 1
                    ;;
            esac
            shift; shift
        done
    elif [ "$#" -gt "0"]; then
        module=$1
        out=$module
        module_rel_path=${srcdir}${module}.c
    else
        echo -e "${LY}No arguments provided${N} --"
        echo -e "${Y}Running with default params${N}"
        echo -e "${B}(module main being built..)${N}"
    fi
}
function print_args() {
    echo -e "${LG}VARS${N}"
    echo -e "${Y}module:${N} $module"
    echo -e "${Y}compiler:${N} $compiler"
    echo -e "${Y}out:${N} $out"
    echo -e "${Y}builddir:${N} $builddir"
    echo -e "${Y}srcdir:${N} $srcdir"
    echo -e "${Y}workdir:${N} $workdir"
}
function print_dur() {
    echo -e "${LG}DURATIONS${N}"
    echo -e "${Y}build:${N} $builddur"
    echo -e "${Y}run:${N} $rundur"
}
function build() {
    start=$(date +%s.%N)
    $buildcmd
    dur=$(echo -e "$(date +%s.%N) - $start" | bc)
    return dur
}
function run() {
    start=$(date +%s.%N)
    $runcmd
    dur=$(echo -e "$(date +%s.%N) - $start" | bc)
    return dur
}
function main() {
    parse_args $@
    buildlen=build
    print_args
    runlen=run


}
