[package]
name = "do-cur"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
cursive = { version = "0.16.3"}
directories-next = "2.0.0"
walkdir = "2.3.2"
